name: Gem Validations

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.3', '3.2', '3.1', '3.0', '2.7', '2.6', '2.5']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler: default
          rubygems: default

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec rspec
